name: BetterDiscordSRV
version: '${project.version}'
main: com.earthpol.betterDiscordSRV.BetterDiscordSRV
api-version: '1.21'
folia-supported: true
commands:
  discord:
    description: Link your Minecraft account to Discord
    usage: /<command> link
